spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: "{cipher}d8d0e8ed67cae5005f16ce9217731cad27a3a1b86f45190c703d0662c785fa08aee0905607e99c5917515bd86308c734"
    username: "{cipher}1ace4ad9d8c5e16ca0856eae24a1ce18eccfd8faa9978adb5782a273e8c22504"
    password: "{cipher}1ace4ad9d8c5e16ca0856eae24a1ce18eccfd8faa9978adb5782a273e8c22504"
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-jiniworld
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: create
    open-in-view: false
    show-sql: true